export enum HumanCyborgRelationsCmd {
  mildHappy = 1,
  extremeHappy = 2,
  mildSad = 3,
  extremeSad = 4,
  mildAngry = 5,
  extremeAngry = 6,
  mildScared = 7,
  extremeScared = 8,
  overload = 9,
  enableMuse = 10,
  disableMuse = 11,
  toggleMuse = 12,
  triggerMusing = 13,
  minSecondsBetweenMusings = 14,
  maxSecondsBetweenMusings = 15,
  playWavOnA = 16,
  playWavOnB = 17,
  playSdRandomOnA = 18,
  playSdRandomOnB = 19,
  panicStop = 20,
  gracefulStop = 21,
  stopWavOnA = 22,
  stopWavOnB = 23,
  vocalizerVolume = 24,
  wavAVolume = 25,
  wavBVolume = 26,
  enableImprov = 27,
  enableCanonical = 28,
  enablePersonalityOverride = 29,
  disablePersonalityOverride = 30,
  zeroEmotions = 31,
  setHappyLevel = 32,
  setSadLevel = 33,
  setMadLevel = 34,
  setScaredLevel = 35,
}

export enum HcrCommandCategory {
  none,
  stimuli,
  muse,
  sdWav,
  stop,
  volume,
  override,
}