services:
  astros:
    image: 'ghcr.io/battlesloth/astros-server:latest'
    restart: unless-stopped
    ports:
      - 80:80
      - 5000:5000
      - 3000:3000
    environment:
      - CORS_ORIGIN=http://localhost
    volumes:
      - /home/astros/.config/astrosserver:/root/.config/astrosserver
    networks:
      - astronet
    devices:
      - 'dev/ttyAMA0:/dev/ttyS0'

networks:
  astronet:
    external: true
